### ISSUE TITLE
Netlify link from Readme file for launching application doesn't work.

### ISSUE THREAD

**Issue by codyfet** [vpodolyan/achieveday#36]

**Comment by vpodolyan** [comment]
Hey @codyfet! Do you mean this link?

![image](https://user-images.githubusercontent.com/7989047/107984875-fe4d5780-6fd9-11eb-85a3-faf11bb0611c.png)


It actually indicates that the last build was successful and lead to the deploys page on Netlify. Please see screenshot below

![image](https://user-images.githubusercontent.com/7989047/107984969-3359aa00-6fda-11eb-90c6-22c0acadcd1a.png)

**Comment by vpodolyan** [comment]
Close as inactive
