### ISSUE TITLE
How to add favourite quote?

### ISSUE THREAD

**Issue by codyfet** [vpodolyan/achieveday#65]
I don't see any suggestiones with quotes.

But I see the screen about it.
<img width="1792" alt="Снимок экрана 2021-12-22 в 22 25 25" src="https://user-images.githubusercontent.com/8351264/147145122-704c624d-e4bc-4c57-b8d0-8ca24078a1a4.png">

**Comment by vpodolyan** [comment]
Good question 🙂  I'll write short instruction shortly

**Comment by vpodolyan** [comment]
Hey @codyfet!

I'm back to you, sorry for a bit late reply.

You can add favourite quote on Achievements page. You just need to write an achievement, then you'll get the quote of day which can be added to the favourites by pressing on stack button near to the quote.

I've also added this message on Favourite Quotes page for clarity.

<img width="884" alt="Screenshot 2022-01-22 at 18 54 49" src="https://user-images.githubusercontent.com/7989047/150646772-ea393986-6c82-47a9-bbc2-15f7317cabdb.png">
